### ISSUE TITLE
Rewrite of the Add-on

### ISSUE THREAD

**Issue by photodiode** [photodiode/panorama-view#123]
I have wanted to rewrite this add-on for a long time, to clean it up and make adding new features much easier, but motivation never descended upon me. Until these last few weeks.  
So here is an issue detailing what has been done and what's left.

The main thing is that I have rewritten how Tab Groups are handled. They are now handled exclusively in the background script, simulating something close to the tabGroups API in chrome and webkit. The functionality of the add-on remains identical, however.
The Panorama View part is now using runtime messages wrapped in some functions, e.g. `addon.tabGroups.query({windowId: viewWindowId});` to communicate to the background script.

The code is still no shining example of programming perfection, but it is heaps better that it was.  
Hopefully that alone has crushed some bugs.

Below is a list of other things I've done, and a few still to do. (this list might change)

### Additions
- [x] Select and move multiple tabs
- [x] Move tabs between windows
- [x] Shortcut for New Tab Group (#63)
- [x] Shortcut for Previous Tab Group (#90, #63)
- [x] "New Tab Group" button added in Panorama View Icon right-click menu
- [x] Dragging one or more tabs to an empty area will create a new Tab Group
- [ ] Redo the backup system
- [ ] #98

### Fixes
- [x] Display shorcut key names correctly on MacOS (#110)
- [x] (#102)
- [x] Dragging a tab from another window closes all but one tab in the window (#75)
- [x] Z ordering of created Tab Groups (#72)
- [ ] Light/dark theme selection (#97)

**Comment by Wrathgaar** [comment]
You're a legend. These tweaks have been a big improvement to what was already one of the best of the best browser extensions around. Thanks for keeping it going!

**Comment by wysocki** [comment]
I could not use Firefox without Panorama! In fact, it's pretty much the main reason for me to use FF!
HOWEVER: I have a problem that I come across too often. It happens when I move a tab to a new window, then close the main window before I close the new window. All my tab groups are gone!!! How can I prevent this from happening and how is best way to recover?
